config/routes.rb
Pushcab::Application.routes.draw do

  devise_for :cabs
  devise_for :users

  resources :taxi_requests, except: :new
  resources :cabs

  resources :taxi_requests, except: :new  do
    post 'response_request'
  end

  match "/my_requests" => "taxi_requests#user_request", :as => :my_requests
  match "/taxi_requests/:cab_id/new" => "taxi_requests#new", :as => :new_taxi_request, via: :post

  root :to => 'home#index'
end

app/models/cab.rb
class Cab < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :authentication_keys => [:login]

  attr_accessor :login
  attr_accessible :email, :password, :password_confirmation, :remember_me, :police_no, :phone_no, :status,
                  :username, :latitude, :longitude

  validates :username, :police_no, :phone_no, :email, :police_no, presence: true, uniqueness: true

  has_many :taxi_requests, dependent: :destroy

  geocoded_by :get_lat_lon   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates
  scope :order_by_username, order("username ASC")

  def self.not_requested_by_user(user)
    ids = TaxiRequest.where(user_id: user.id).pluck(:cab_id)
    ids.blank? ? self.all : self.where("id NOT IN (?)", ids)
  end

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {:value => login.downcase}]).first
    else
      where(conditions).first
    end
  end

  def get_lat_lon
    puts "get latitude and longitude"
  end

end

app/models/taxi_request.rb
class TaxiRequest < ActiveRecord::Base
  attr_accessible :cab_id, :pickup_location, :pickup_time, :status, :user_id, :latitude, :longitude

  belongs_to :user
  belongs_to :cab

  scope :pending, where(status: "pending")
end

app/models/user.rb
class User < ActiveRecord::Base
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :timeoutable, :token_authenticatable, :confirmable,
         :authentication_keys => [:login]

  attr_accessor :login
  attr_accessible :email, :password, :password_confirmation, :remember_me, :confirmed_at,
                  :phone_no, :username, :login

  validates :phone_no, :username, presence: true, uniqueness: true

  has_many :taxi_requests, dependent: :destroy

  def self.find_first_by_auth_conditions(warden_conditions)
    conditions = warden_conditions.dup
    if login = conditions.delete(:login)
      where(conditions).where(["lower(username) = :value OR lower(email) = :value", {:value => login.downcase}]).first
    else
      where(conditions).first
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
  before_filter :authenticate_any!

  def authenticate_any!
    if cab_signed_in?
      true
    else
      authenticate_user!
    end
  end

  def user_login?
    user_signed_in? || cab_signed_in?
  end

  def current_login
    if user_signed_in? || cab_signed_in?
     user = current_user ?  current_user : current_cab
    end
  end

  def get_lat_lon
    my_ll = if Rails.env.eql?("development")
              [40.723323, -73.998413]
            else
              geoip = Geocoder.search(request.ip)
              lat = geoip.first.data["latitude"]
              lon = geoip.first.data["longitude"]
              [lat, lon]
            end
    p "My lat lon: ------#{my_ll}-------"
    my_ll = my_ll
  end
end

app/controllers/cabs_controller.rb
class CabsController < ApplicationController

  def show
    @cab = Cab.find(params[:id])
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  skip_before_filter :authenticate_any!
  before_filter :current_login, :only => [:index]

  def index
    my_ll = get_lat_lon
    current_login.update_attributes(latitude: my_ll[0], :longitude => my_ll[1]) if user_login?
  end
end

app/controllers/taxi_requests_controller.rb
class TaxiRequestsController < InheritedResources::Base

  def index
    #@cabs = Cab.near([current_login.latitude, current_login.longitude], 20, :units => :km)
    #@cabs = Cab.not_requested_by_user(current_login).order_by_username
    @cabs = Cab.order_by_username
  end

  def new
    request  = current_user.taxi_requests.new(cab_id: params[:cab_id])
    alert_type, msg = request.save  ? [:notice, "Request was sent"]  : [:error, "Failed to send request"]
    flash[alert_type] = msg

    redirect_to taxi_requests_url
  end

  def user_request
    @my_requests = current_cab ? current_login.taxi_requests.pending : current_login.taxi_requests
  end

  def response_request
    msg case params[:response]
      when 'approved'
        TaxiRequest.update_all({status: "step1"}, {id: params[:taxi_request_id]})
        "Confirmation was sent"
      when 'declined'
        TaxiRequest.delete(params[:taxi_request_id])
        "Request was declined"
    end

    redirect_to my_requests_url, notice: msg
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def status(resource)
    resource.status
  end

  def format_date(time)
    time ? time.strftime("%d/%b/%Y") : "UNKNOWN"
  end

  def taxi_status(resource)
    requests = TaxiRequest.where(user_id: current_login, cab_id: resource.id, status: "pending")
    if requests.blank?
      resource.status.eql?("available") ? "success" : "error"
    else
      "error"
    end

  end

  def current_login
    if user_signed_in? || cab_signed_in?
      user = current_user ?  current_user : current_cab
    end
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/taxi_requests_helper.rb
module TaxiRequestsHelper
end

app/views/cabs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
    <b>Driver:</b>
    <%= @cab.username %>
</p>

<p>
    <b>Status:</b>
    <%= @cab.status %>
</p>

<p>
    <b>Police no:</b>
    <%= @cab.police_no %>
</p>

<p>
    <div id="map"></div>
</p>

<%= content_for :javascript do %>
    <script type="text/javascript">
        var map;
        var lat = <%= @cab.latitude %>
        var lng = <%= @cab.longitude %>

        $(document).ready(function(){
            map = new GMaps({
                div: '#map',
                lat: lat,
                lng: lng
            });

            map.addMarker({
                lat: lat,
                lng: lng,
                title: "<%= @cab.try(:username) %>",
                click: function(e) {
                    alert('You clicked in this marker');
                }
            });

        });
    </script>
<% end %>

app/views/home/index.html.erb
<h1>Welcome !!</h1>
<p>
  <% if !user_signed_in? and !cab_signed_in? %>
    Login As :
    <%= link_to "Driver", new_cab_session_path %>
    OR
    <%= link_to "Passanger", new_user_session_path %>
  <% end %>
</p>

<% if user_signed_in? %>
    <p>
      <h3>You are at:</h3>
      <div id="map"></div>
    </p>

    <%= content_for :javascript do %>
        <script type="text/javascript">
            var map;
            var lat = <%= current_login.latitude %>
            var lng = <%= current_login.longitude %>

            $(document).ready(function(){
                map = new GMaps({
                    div: '#map',
                    lat: lat,
                    lng: lng
                });

                map.addMarker({
                    lat: lat,
                    lng: lng,
                    title: "<%= current_login.try(:username) %>",
                    click: function(e) {
                        alert('You clicked in this marker');
                    }
                });

                GMaps.geolocate({
                    success: function(position){
                        map.setCenter(position.coords.latitude, position.coords.longitude);
                    },
                    error: function(error){
                        alert('Geolocation failed: '+error.message);
                    },
                    not_supported: function(){
                        alert("Your browser does not support geolocation");
                    },
                    always: function(){
                        alert("Done!");
                    }
                });

            });
        </script>
    <% end %>
<% end %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Pushcab", root_path, :class => 'brand' %>
<% if user_signed_in? or cab_signed_in? %>
    <ul class="nav nav-pills pull-right">
      <% if current_user %>
          <li>
            <%= link_to 'CABS', taxi_requests_path %>
          </li>
      <% end %>

      <li class="dropdown" id="menu1">
        <a class="dropdown-toggle" data-toggle="dropdown" href="#menu1">
          My Account
          <b class="caret"></b>
        </a>
        <ul class="dropdown-menu">
          <li>
            <%= link_to 'Edit account', send("edit_#{current_user ? 'user' : 'cab'}_registration_path") %>
          </li>
              <li>
                <%= link_to 'My Requests', my_requests_path %>
              </li>
          <li class="divider"></li>
          <li>
            <%= link_to 'Logout', destroy_user_session_path, :method => 'delete' %>
          </li>
        </ul>
      </li>
    </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Pushcab" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Pushcab" %>">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body class="<%= controller_name %> <%= action_name %>">
    <div class="navbar navbar-fixed-top navbar-inverse">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </div>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
    <%= javascript_include_tag "application" %>
    <%= yield :javascript %>
  </body>
</html>

<!-- test change -->

app/views/taxi_requests/_cab_requests.html.erb
<br>
<h1>List Request</h1>
<table class="table table-bordered table-stripped table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>Username</th>
    <th>Status</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @my_requests.each_with_index do |request, i| %>
      <% counter = i+1 %>
      <tr class="success">
        <td><%= counter %></td>
        <td><%= request.user.username || "Anonymous" %></td>
        <td><%= status(request) %></td>
        <td>
          <%= link_to "Approve", taxi_request_response_request_path(request.id, response: "approved"), class: "btn btn-mini btn-primary", confirm: "Are you sure?", method: :post %> |
        <%= link_to "Decline", taxi_request_response_request_path(request.id, response: "declined"), class: "btn btn-mini btn-danger", confirm: "Are you sure?", method: :post %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/taxi_requests/_form.html.erb
<%= simple_form_for(@taxi_request) do |f| %>
    <% unless @taxi_request.new_record? %>
        <%= f.error_notification %>

        <div class="form-inputs">
          <%= f.input :cab_id %>
          <%= f.input :pickup_location %>
          <%= f.input :pickup_time, as: :string, input_html: {class: "datepicker"} %>
        </div>

        <div class="form-actions">
          <%= f.button :submit %>
        </div>
    <% end %>
<% end %>

app/views/taxi_requests/edit.html.erb
<h1>Editing taxi_request</h1>

<%= render 'form' %>

<%= link_to 'Show', @taxi_request %> |
<%= link_to 'Back', taxi_requests_path %>

app/views/taxi_requests/index.html.erb
<br>
<h1>Cabs</h1>
<table class="table table-bordered table-stripped table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>Taxi No.</th>
    <th>Driver Name</th>
    <th>Status</th>
    <th>Maps</th>
    <th>Action</th>
  </tr>
  </thead>
  <tbody>
  <% @cabs.each_with_index do |cab, i| %>
      <% counter = i+1 %>
      <tr class="<%= taxi_status(cab) %>">
        <td><%= counter %></td>
        <td><%= cab.police_no %></td>
        <td><%= cab.username || "Anonymous" %></td>
        <td><%= status(cab) %></td>
        <td><%= link_to image_tag("/assets/icon-map.png"), cab_path(cab) %></td>
        <td><%= link_to "send request", new_taxi_request_path(cab), class: "btn btn-mini btn-info", confirm: "Are you sure?", method: :post unless taxi_status(cab).eql?("error") %></td>
        </tr>
  <% end %>
  </tbody>
</table>

app/views/taxi_requests/new.html.erb
<h1>New Request</h1>

<%= render 'form' %>

<%= link_to 'Back', taxi_requests_path %>

app/views/taxi_requests/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>User:</b>
  <%= @taxi_request.user_id %>
</p>

<p>
  <b>Driver:</b>
  <%= @taxi_request.cab_id %>
</p>

<p>
  <b>Status:</b>
  <%= @taxi_request.status %>
</p>

<p>
  <b>Pickup location:</b>
  <%= @taxi_request.pickup_location %>
</p>

<p>
  <b>Pickup time:</b>
  <%= @taxi_request.pickup_time %>
</p>


<%= link_to 'Edit', edit_taxi_request_path(@taxi_request) %> |
<%= link_to 'Back', taxi_requests_path %>

app/views/taxi_requests/user_request.html.erb
<%= render "#{current_login.class.to_s.singularize.downcase}_requests" %>

app/views/taxi_requests/user_requests.html.erb
<div><%= link_to "New Request", taxi_requests_path, class: "btn btn-primary" %></div>
<br>
<table class="table table-bordered table-stripped table-hover">
  <thead>
  <tr>
    <th>#</th>
    <th>CAB No.</th>
    <th>Pickup Location</th>
    <th>Pickup Time</th>
    <th>Status</th>
  </tr>
  </thead>
  <tbody>
  <% @my_requests.each_with_index do |request, i| %>
      <% counter = i+1 %>
      <tr class="<%= status(request) %>">
        <td><%= counter %></td>
        <td><%= request.cab.try(:police_no) %></td>
        <td><%= request.pickup_location || "UNKNOWN" %></td>
        <td><%= format_date(request.pickup_time) %></td>
        <td><%= status(request) %></td>
      </tr>
  <% end %>
  </tbody>
</table>